DROP DATABASE HOSPITAL;
CREATE SCHEMA IF NOT EXISTS HOSPITAL;

USE HOSPITAL;

CREATE TABLE IF NOT EXISTS CARGO( 
ID_CARGO INT(11),
PRIMARY KEY(ID_CARGO),
NOME VARCHAR(45) NOT NULL
);
CREATE TABLE IF NOT EXISTS RISCOS_OCUPACIONAIS(
ID_RISCOS INT(11),
PRIMARY KEY(ID_RISCOS),
NOME VARCHAR(11) NOT NULL
);
CREATE TABLE IF NOT EXISTS RESULTADO_EXAME(
ID_TIPO_RESULTADO_EXAME INT(11) PRIMARY KEY,
TIPO VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS TIPO_EXAME(
ID_TIPO_EXAME INT(11) PRIMARY KEY,
TIPO VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS MEDICO(
ID_MEDICO INT(11) PRIMARY KEY,
CRM INT(110) NOT NULL,
CPF VARCHAR(20) NOT NULL,
ESPECIALIDADE VARCHAR(50),
DATA_DE_NASCIMENTO DATE  NOT NULL,
ENDERECO VARCHAR (200) NOT NULL,
TELEFONE VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS EMPRESA(
ID_EMPRESA INT(11) PRIMARY KEY,
CNPJ VARCHAR(20) NOT NULL,
NOME_FANTASIA VARCHAR(20) NOT NULL,
ENDERECO VARCHAR(20) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
EMPRESA_ID_EMPRESA INT(11) NOT NULL,
CONSTRAINT EMPR_EMPR FOREIGN KEY(EMPRESA_ID_EMPRESA)
 REFERENCES EMPRESA(ID_EMPRESA)
 );
CREATE TABLE IF NOT EXISTS FUNCIONARIO(
ID_FUNCIONARIO INT(11) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR	(20) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
ENDERECO VARCHAR(200) NOT NULL,
TELEFONE VARCHAR (20) NOT NULL,
CARGO_ID_CARGO INT(11) not null,
EMPRESA_ID_EMPRESA INT(11)not null,
CONSTRAINT CAR_FUN FOREIGN KEY(CARGO_ID_CARGO) 
REFERENCES CARGO(ID_CARGO),
CONSTRAINT EMP_FUN FOREIGN KEY(EMPRESA_ID_EMPRESA) 
REFERENCES EMPRESA(ID_EMPRESA)
);
CREATE TABLE IF NOT EXISTS ATESTADO(
ID_ATESTADO INT(11) NOT NULL PRIMARY KEY,
RESULTADOS_RISCOS VARCHAR(100) NOT NULL,
RESULTADO VARCHAR(50) NOT NULL,
OBSERVADORES VARCHAR (300) NOT NULL,
MEDICO INT(11),
CONSTRAINT MED_ATE FOREIGN KEY(MEDICO) REFERENCES MEDICO(ID_MEDICO)
);
CREATE TABLE IF NOT EXISTS EMPRESA(
ID_EMPRESA INT(11) NOT NULL PRIMARY KEY,
ID_EMPRESA INT(11) NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
NOME_FANTASIA VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(200) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
FOREIGN KEY (IMPRESA_ID) REFERENCES EMPRESA(ID_EMPRESA)
);
CREATE TABLE IF NOT EXISTS EXAME(
ID_EXAME INT(11) NOT NULL PRIMARY KEY,
ESPECIALIDADE VARCHAR (50) NOT NULL,
DATA_REALIZACAO DATE NOT NULL, 
TIPO_EXAME INT(11) NOT NULL,
RESULTADO_EXAME INT(11) NOT NULL,
CONSTRAINT TIP_EXA FOREIGN KEY(TIPO_EXAME) REFERENCES TIPO_EXAME(ID_TIPO_EXAME),
CONSTRAINT RES_EXA FOREIGN KEY(RESULTADO_EXAME) REFERENCES RESULTADO_EXAME(ID_TIPO_RESULTADO_EXAME)
);
CREATE TABLE IF NOT EXISTS CARGOS_HAS_RISCOS_OCUPACIONAIS(
ID_RISCO INT(11),
ID_CARGO INT(11),
PRIMARY KEY(ID_RISCO,ID_CARGO),
CONSTRAINT RISCO_CARGO FOREIGN KEY(ID_RISCO) 
REFERENCES RISCOS_OCUPACIONAIS(ID_RISCO),
CONSTRAINT CARGO_RISCO FOREIGN KEY(ID_CARGO)
REFERENCES CARGO(ID_CARGO)
);
CREATE TABLE IF NOT EXISTS EXAME_HAS_ATESTADO(
EXAME_ID INT NOT NULL,
ATESTADO_ID INT NOT NULL,
PRIMARY KEY(EXAME_ID, ATESTADO_ID),
FOREIGN KEY (EXAME_ID) REFERENCES EXAMES(EXAMES_ID),
FOREIGN KEY (ATESTADO_ID) REFERENCES ATESTADOS (ATESTADO)
);
CREATE TABLE IF NOT EXISTS FUNCIONARIO_HAS_EXAME(
EXAME_ID_EXAME INT(11) NOT NULL,
FUNCIONARIO_ID_FUNCIONARIO INT(11) NOT NULL,
PRIMARY KEY(EXAME_ID_EXAME,FUNCIONARIO_ID_FUNCIONARIO),
CONSTRAINT EXA_FUN FOREIGN KEY(EXAME_ID_EXAME) REFERENCES EXAMES(ID_EXAME),
CONSTRAINT FUN_EXA FOREIGN KEY(FUNCIONARIO_ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS EMPRESA_EXAME(
EXAME_ID_EXAME INT(11) NOT NULL,
EMPRESA_ID_EMPRESA INT(11) NOT NULL,
PRIMARY KEY(EXAME_ID_EXAME,EMPRESA_ID_EMPRESA),
CONSTRAINT EXA_EMP FOREIGN KEY(EXAME_ID_EXAME) REFERENCES EXAMES(ID_EXAME),
CONSTRAINT EMP_EXA FOREIGN KEY(EMPRESA_ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);
