CREATE SCHEMA IF NOT EXISTS HOSPITAL;

 USE HOSPITAL;

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
ID_FUNCIONARIO INT(11) NOT NULL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR	(20) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
ENDERECO VARCHAR(200) NOT NULL,
TELEFONE VARCHAR (20) NOT NULL,
FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO) , 
FOREIGN KEY (IMPRESA_ID) REFERENCES EMPRESA(ID_EMPRESA)
);
CREATE TABLE IF NOT EXISTS EMPRESA(
ID_EMPRESA INT(11) NOT NULL PRIMARY KEY,
CNPJ VARCHAR(20) NOT NULL,
NOME_FANTASIA VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(200) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
FOREIGN KEY (IMPRESA_ID) REFERENCES EMPRESA(ID_EMPRESA)
);
CREATE TABLE IF NOT EXISTS CARGO( 
ID_CARGO INT(11) NOT NULL PRIMARY KEY,
NAME VARCHAR(45) NOT NULL
);
CREATE TABLE IF NOT EXISTS FUNCIONARIO_HAS_EXAME(
FOREIGN KEY (EXAME_ID) REFERENCES EXAMES(EXAME_ID),
FOREIGN KEY (FUNCIONARIO_ID)  REFERENCES FUNCIONARIO(FUNCIONARO_ID)
);
CREATE TABLE IF NOT EXISTS EXAME(
ID_EXAME INT(11) NOT NULL PRIMARY KEY,
ESPECIALIDADE VARCHAR (50) NOT NULL,
DATA_REALIZACAO DATE NOT NULL, 
FOREIGN KEY (ID_TIPO_EXAME)  REFERENCES TIPO(ID_TIPO_EXAME)
);
CREATE TABLE IF NOT EXISTS RESULTADO_EXAME(
ID_TIPO_RESULTADO_EXAME INT (11) PRIMARY KEY,
TIPO VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS TIPO_EXAME(
ID_TIPO_EXAME INT(11) NOT NULL PRIMARY KEY,
TIPO VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS ATESTADO(
ID_ATESTADO INT(11) NOT NULL PRIMARY KEY,
RESULTADOS_RISCOS VARCHAR(100) NOT NULL,
RESULTADO VARCHAR(50) NOT NULL,
OBSERVADORES VARCHAR (300) NOT NULL,
FOREIGN KEY (MEDICO_ID) REFERENCES MEDICO(MEDICO_ID)
);
CREATE TABLE IF NOT EXISTS EXAME_HAS_ATESTADO(
EXAME_ID INT NOT NULL,
ATESTADO_ID INT NOT NULL,
PRIMARY KEY(EXAME_ID, ATESTADO_ID),
FOREIGN KEY (EXAME_ID) REFERENCES EXAMES(EXAMES_ID),
FOREIGN KEY (ATESTADO_ID) REFERENCES ATESTADOS (ATESTADO)
);
CREATE TABLE IF NOT EXISTS MEDICO(
MEDICO_ID INT(11) NOT NULL PRIMARY KEY,
CRM INT(110) NOT NULL,
CPF VARCHAR(20) NOT NULL,
ESPECIALIDADE VARCHAR(50),
DATA_DE_NASCIMENTO DATE  NOT NULL,
ENDERECO VARCHAR (200) NOT NULL,
TELEFONE VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS RISCOS_OCUPACIONAIS(
ID_RISCOS INT(11) NOT NULL PRIMARY KEY,
NOME VARCHAR(11) NOT NULL
);
CREATE TABLE IF NOT EXISTS CARGOS_HAS_RISCOS_OCUPACIONAIS(
FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
FOREIGN KEY (RISCOS_OCUACIONAIS_ID) REFERENCES RISCOS_OCUPACIONAIS(RISCOS_OCUACIONAIS_ID)
);











